export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  INVALID_FILE_SIGNATURE: 'INVALID_FILE_SIGNATURE',
  CONVERSION_TIMEOUT: 'CONVERSION_TIMEOUT',
  CONVERSION_FAILED: 'CONVERSION_FAILED',
  PDF_VALIDATION_FAILED: 'PDF_VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS: Record<ErrorCode, number> = {
  INVALID_REQUEST: 400,
  FILE_REQUIRED: 400,
  FILE_TOO_LARGE: 413,
  UNSUPPORTED_FILE_TYPE: 415,
  INVALID_FILE_SIGNATURE: 415,
  CONVERSION_TIMEOUT: 504,
  CONVERSION_FAILED: 422,
  PDF_VALIDATION_FAILED: 422,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};
